kind: List
apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: k8s-dns
    namespace: kube-system
    labels:
      kubernetes.io/name: "Kubernetes-DNS"
      kubernetes.io/cluster-service: "true"
  spec:
    selector:
      app: k8s-dns
    clusterIP: 10.0.0.10
    ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
